### ISSUE TITLE
Add support for Python 3.14

### ISSUE THREAD

**Issue by sydney-runkle** [langchain-ai/langgraph#5253]
* Add to CI matrices
* Confirm all tests are passing

**Comment by YassinNouh21** [comment]
Hi @sydney-runkle ! I'd like to suggest a staged approach for adding Python 3.14 support, given that 3.14.0 final won't be released until October 2025:

Immediate Action: Alpha Testing (Phase 1)

Since Python 3.14.0a1 is already available, we could start with experimental support:

**CI Matrix Updates**
Update both `.github/workflows/_test.yml` and `.github/workflows/_test_langgraph.yml`:

```yaml
strategy:
  matrix:
    python-version:
      - "3.9"
      - "3.10" 
      - "3.11"
      - "3.12"
      - "3.13"
      - "3.14-dev"  # Allow early testing
    include:
      - python-version: "3.14-dev"
        experimental: true
```

Add failure tolerance for experimental versions:
```yaml  
continue-on-error: ${{ matrix.experimental || false }}
```

 **CLI Configuration Support**  
Update `libs/cli/langgraph_cli/config.py` constants and `libs/cli/generate_schema.py`:

**In config.py** (~line 13-14):
```python  
MIN_PYTHON_VERSION = "3.11"
DEFAULT_PYTHON_VERSION = "3.11" 
```

**In generate_schema.py** (~line 165):
```python
python_schema["properties"]["python_version"]["enum"] = ["3.11", "3.12", "3.13", "3.14"]
```
